import type { NextPage } from "next";
import Head from "next/head";
import { useRef } from "react";

import fs from "fs";
import matter from "gray-matter";

import Banner from "../src/components/Banner";
import BottomNav from "../src/components/BottomNav";
import BottomNavAction from "../src/components/BottomNavAction";
import { CirclePersonIcon, ResumeIcon, WorkerIcon } from "../src/icons";
import Section from "../src/layout/Section";
import { MarkdownSection } from "../src/components/MarkdownSection";
import ProgresBar from "../src/components/ProgresBar";
import useScrollPrgores from "../src/hooks/useScrollPrgores";

export async function getStaticProps() {
  let aboutMeSection;

  try {
    const readFile = fs.readFileSync(`content/aboutme.md`, "utf-8");
    const { data, content } = matter(readFile);
    aboutMeSection = {
      data,
      content,
    };
  } catch (e) {
    console.error(e);
  }

  return {
    props: {
      aboutMeSection,
    },
  };
}

interface HomePageProps {
  aboutMeSection?: {
    data: {
      title: string;
    };
    content: any;
  };
}

const Home: NextPage<HomePageProps> = ({ aboutMeSection }) => {
  const aboutMeRef = useRef<HTMLElement | null>(null);
  const myProjects = useRef<HTMLElement | null>(null);
  const contactMe = useRef<HTMLElement | null>(null);
  const pageProggres = useScrollPrgores();

  const scrolToRef = (ref: React.RefObject<HTMLElement>) => {
    ref.current?.scrollIntoView({
      behavior: "smooth",
      block: "start",
    });
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {pageProggres && <ProgresBar progress={pageProggres} />}
      <Banner title="Hi I'm Ernest, a web developer" />
      <div className="m-7 overflow-hidden">
        {aboutMeSection && (
          <Section title={aboutMeSection.data.title} ref={aboutMeRef}>
            <MarkdownSection content={aboutMeSection.content} />
          </Section>
        )}
        {aboutMeSection && (
          <Section title={aboutMeSection.data.title} ref={aboutMeRef}>
            <MarkdownSection content={aboutMeSection.content} />
          </Section>
        )}
        {aboutMeSection && (
          <Section title={aboutMeSection.data.title} ref={aboutMeRef}>
            <MarkdownSection content={aboutMeSection.content} />
          </Section>
        )}
      </div>
      <BottomNav>
        <BottomNavAction
          icon={<CirclePersonIcon />}
          label="About Me"
          action={() => {
            scrolToRef(aboutMeRef);
          }}
        />
        <BottomNavAction
          icon={<WorkerIcon />}
          label="Projects"
          action={() => {
            scrolToRef(myProjects);
          }}
          isActive={true}
        />
        <BottomNavAction
          icon={<ResumeIcon />}
          label="Resume"
          action={() => {
            scrolToRef(contactMe);
          }}
        />
      </BottomNav>
    </div>
  );
};

export default Home;
